### ISSUE TITLE
imported records don't show info when clicked on map

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#117]
Not sure if this is a a bug or a feature...

View the demo acacia tree in Phylolink:

http://phylolink.ala.org.au/phylo/show/274#node/395373a92f9db36c18fc0845ebcf9db5

and then click the "map" tab and click the "view in Spatial Portal" button:

http://spatial.ala.org.au/?&q=qid:1449098552885&cm=taxon_name&qname=Phylolink&ws=http://biocache.ala.org.au/&bs=http://biocache.ala.org.au/ws

Occurrence records in the SP cannot be clicked on to view details... click does nothing. These

**Comment by djtfmartin** [comment]
Looks like a bug, but not sure what the cause is. The URL params look ok to me...

**Comment by Tasilee** [comment]
Earlier this morning Phylolink wasn't display any occurrences ont he map, but as of just now it is, and the display of metadata of the records in the SP looks ok, but when you click on the "More details: all records at this point", you get "No records found"
![capture](https://cloud.githubusercontent.com/assets/6656350/11616016/c9058280-9cc3-11e5-8275-bb403468d33a.jpg)
![capture_2](https://cloud.githubusercontent.com/assets/6656350/11616018/d271dbde-9cc3-11e5-838c-75dd1309d88b.jpg)

**Comment by adam-collins** [comment]
For some reason the mapped points are not applying the fq that is in the qid. This results in points appearing on the map that you cannot click because they are filtered out by the fq in the point click query.

It is now mapping correct on SP dev using the params above http://spatial-dev.ala.org.au/?&q=qid:1449098552885&cm=taxon_name&qname=Phylolink&ws=http://biocache.ala.org.au/&bs=http://biocache.ala.org.au/ws

Without an example URL I'm not sure what the 'no records found' issue is.

**Comment by Tasilee** [comment]
A test suggests this is now working ok. Details of record shown in biocache.
![capture](https://cloud.githubusercontent.com/assets/6656350/16905500/136d74dc-4cea-11e6-8df2-60d26dd7425d.jpg)
