### ISSUE TITLE
Area report 'Threatened species' list needs conservation status

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#50]
Can't currently identify the nature of the conservation status on the list of "Threatened species" in the area reports. Need to add a column (or more?) with ALL threatened status listed. This is important if users are to assess conservation status.
![capture_6](https://cloud.githubusercontent.com/assets/6656350/5307872/8f2e4120-7c65-11e4-8b71-bce71359344a.jpg)

**Comment by adam-collins** [comment]
Including a flag to indicate a species (lsid) was found in one of the species lists defined in the config file.

On dev.

**Comment by Tasilee** [comment]
It appears that species in the 'Threatened' list are in many cases also incorrectly flagged as 'Invasive', e.g., Rostratula australis, some species such as Varanus varius are in the threatened list but not flagged as 'threatened' but are flagged for Invasive while some species such as Struthidea cinerea are listed but not flagged as either 'threatened' or 'invasive'

Area 

POLYGON((142.05810546876 -34.36968394778,142.59643554688 -34.36968394778,142.59643554688 -33.978843290667,142.05810546876 -33.978843290667,142.05810546876 -34.36968394778))

**Comment by adam-collins** [comment]
dr967 and dr1782 where matching as Invasive instead of Conservation. Struthidea cinerea might be tricky because lists.ala has matched it against the subspecies. 

Working on replacing the 'Y' flag with all matching list names.

Not sure what list dr71 is.

One of the invasive lists required is marked as private. Can we include matches against this one?

Area report items 'Theatened species (all lists)' and 'Invasive species (all lists)' are incorrectly named. Not sure if replacing (all lists) with (sensitive lists only) makes sense.

**Comment by Tasilee** [comment]
I managed to get some of those lists mixed so sending definitive list via email and below.

Any conservation status-
![image](https://cloud.githubusercontent.com/assets/6656350/6679678/9aa5f9b4-cc9f-11e4-86f9-b62d01df6298.png)

Any 'invasive' status-

![image](https://cloud.githubusercontent.com/assets/6656350/6679685/c391f774-cc9f-11e4-8c27-bd90cf6a57c2.png)

**Comment by adam-collins** [comment]
Is this done now?

**Comment by Tasilee** [comment]
Yes, if any List is marked 'Authoritative' and 'Threatened' or 'Authoritative' and 'Invasive'.
