### ISSUE TITLE
Error when adding WMS Layer

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#66]
This could be a fault with URL or source, but the error message could probably be more informative.

URL used

http://lasigpublic.nerc-lancaster.ac.uk/arcgis/services/EIDCHub/DigitalRivers50K/MapServer/WMSServer

![screen shot 2015-01-23 at 2 48 40 pm](https://cloud.githubusercontent.com/assets/444897/5869542/0a980786-a30f-11e4-815d-fa17478a9e97.png)

**Comment by adam-collins** [comment]
Missing dependency added.

The correct url for Load All Layers option is: http://lasigpublic.nerc-lancaster.ac.uk/arcgis/services/EIDCHub/DigitalRivers50K/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities but because the response contains an invalid url somewhere it won't work.

Instead use the Single Layer Get Map request option. There are 4 layers:
http://lasigpublic.nerc-lancaster.ac.uk/arcgis/services/EIDCHub/DigitalRivers50K/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=HY.PhysicalWaters.WaterBodies.Misc&FORMAT=image/png
http://lasigpublic.nerc-lancaster.ac.uk/arcgis/services/EIDCHub/DigitalRivers50K/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=HY.PhysicalWaters.WaterBodies.Misc&FORMAT=image/png
http://lasigpublic.nerc-lancaster.ac.uk/arcgis/services/EIDCHub/DigitalRivers50K/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=HY.PhysicalWaters.WaterBodies.Canals&FORMAT=image/png
http://lasigpublic.nerc-lancaster.ac.uk/arcgis/services/EIDCHub/DigitalRivers50K/MapServer/WMSServer?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=HY.PhysicalWaters.WaterBodies.Pipes&FORMAT=image/png

**Comment by adam-collins** [comment]
fixed
