### ISSUE TITLE
dev: Area report error in # endemics

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#87]
See attached. # Endemics > # species
![capture_5](https://cloud.githubusercontent.com/assets/6656350/6590328/581444ee-c802-11e4-8a89-f8d69906b9a3.jpg)

**Comment by adam-collins** [comment]
Hi Lee

Please keep going. 

- The endemic issue on dev is because it is using the old biocache-service endemic web service. The new biocache endemic web service is not deployed yet. Production spatial-portal is using SP endemic calculation because of this.
- Merging areas does not show the environmental envelope area as an option. This is because, worst-case, the environmental envelope can be enormous, GBs. Maybe identifying the size of the WKT is an option so a can use/cannot use identifier can be displayed.

I’ll send you an email before I update dev.

Adam

**Comment by adam-collins** [comment]
Intentional on dev for the short term.

**Comment by Tasilee** [comment]
? Will it be fixed on prod update?
